version: '3'

services:
  mysqldb:
    image: mysql
    container_name: seek-candidate-db
    ports:
      - 3307:3306
    expose:
      - '3306'
    environment:
      - MYSQL_DATABASE=candidate_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data: